{% set name = "spectra" %}
{% set version = "0.1.0" %}
{% set sha256 = "6a30e33241cb18256020395181cb4cc029dcac6de6f8d78cecbed81c14226a3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - colormath >=3.0.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - spectra

about:
  home: http://github.com/jsvine/spectra
  summary: 'Color scales and color conversion made easy for Python.'
  description: |
    Spectra is a Python library that makes color math, color scales,
    and color-space conversion easy. It has support for Color scales,
    Color ranges, Color blending, Brightening/darkening colors,
    Saturating/desaturating colors and Conversion to/from multiple color spaces.
    Spectra is built on colormath and grapefruit. Spectra is enormously
    inspired by chroma.js and d3's scales.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/jsvine/spectra
  doc_url: https://github.com/jsvine/spectra

extra:
  recipe-maintainers:
    - ewels
