{% set name = "spectra" %}
{% set version = "0.0.10" %}
{% set sha256 = "31300e339d88a051cccfa174e22a0e5317553c048434869196b2ab7b70dcf091" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - networkx=2.0
    - colormath=3.0.0

test:
  imports:
    - spectra

about:
  home: http://github.com/jsvine/spectra
  summary: 'Color scales and color conversion made easy for Python.'
  description: |
    Spectra is a Python library that makes color math, color scales,
    and color-space conversion easy. It has support for Color scales,
    Color ranges, Color blending, Brightening/darkening colors,
    Saturating/desaturating colors and Conversion to/from multiple color spaces.
    Spectra is built on colormath and grapefruit. Spectra is enormously
    inspired by chroma.js and d3's scales.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/jsvine/spectra
  doc_url: https://github.com/jsvine/spectra

extra:
  recipe-maintainers:
    - ewels
