travis:
  secure:
    BINSTAR_TOKEN: YxS3qRzagG2C0egbcpI1Fr6BxvBVweelsXW2T/bP/wOZUr8qqh2C5idCPQOLQiPTwML6s5Anij0UC8UZRY4bSkrPlce1EVXS3WDTlhFqOaw0clHRff1JmDb522Pkv+grYrDBJpEwuJdw/h5nJXSJ5l3d6SYwndJhY6m+1fGkGDFM/eOg4gYB9Guwqyu0odbId78n6ZGXpH76EwtV2zuVFGejqb6USraEw91DcELxG5ktlJMn+p3yv6Rsj9qY2CEw/z0IZDrsc+aZY78VWuiLKQrq1XCENaxj0MfkvdeFbVjo0K/6Ze/kx18UI3f3SjthONXJe06iQ3SCISGqhcYz/ajI1ZMTGRoE7lxEFu2evIjDcKKLT4f47UNkow65Wo/TkSRrjyhYRQPocXUM/A1AC42Ie+XUpLjB1Ln5xHmDxUgchSxuZnmP/D4/CBULr4B9VzVOx3Oslwq7H3kqrlbFLCGoGhSXf9UpTaOjptiwWjsAq/n7JCMy79x41CerLysqqDtwXdkbmWU+Z9rhgxFDkLQQhht/O6NDr6x/WjAZkc2WgVKPpfYnpp3SEloC8QETwy9K2FDEEo7V12vo1ah+ndSq5BCuuTXFrESoPy/4LMqmsnIzBSm/NNFZ1SczYyVeWIbCzJ9j0GIWVhy6MKQgkHlK6XW374Ox89kkhablRoU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
