travis:
  secure:
    BINSTAR_TOKEN: SC61WUlGl/+KLJ0j9lxg6IGiUnxsGzzrBLVpXVCS56fC9mmqGFJHCL3jtQ6+/EUXAvyrvHRQdQ9VcnGoSMgOQ14t1Vp9Y3L1BQlhDQvijG78OE07M7zNUPLPRTARqWCv+7BSk5M5WbU9vbg+bnGasRFsmd6gsh0Dkizgmg3nZKxxHGyLlCotDkVelpr/B6SfZNNWR4ODhDQITb7b7eNBqJ3jwDqe2AG3SpPlt4a6nksK6s3cUojt053dBBeag4opR6E+tGJFvtlt2BtdRaHccOjNXjzQrlFzFzKDYQxnkY6GqTcXWGW9/YiqyzYhdcp1o3vAISU37ahF5Slm74T98x36+uWd7ipEDmEqj+tMNXdyNbqOeFCUKrVFaEMTKrIV1YUEVokKDSNmQz32L6A49ztMAuI3BJcOL6cGMae8JG3VpIFEb94locF40jXllhxLk60+ivLSM6QRe6zGr2QUaiVRXOkASLLVWbyueJua/CluyzN2YL0MLRHH8nFp3ePHQIaggFELGu5M61lcT6S4qDMb0y+LdFPehiasPfTtakvKGmo2J8L+x6J+ilCiwRyPvD07MWrP/cSFYmA2SVQrfU25SkDe58kuO11jt024rDaw/vdnYw7Zz6LLt5Oh3gs7BPrUZsHbYo3tUSumrWdVl3jBsCtCeBztWc5G1BFVRZ8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
