travis:
  secure:
    BINSTAR_TOKEN: V8IKxwtF7mwSvNcIexNizQyxn3vqskYTEruZrrwP8nEyRoR/n/l+aY8eHmaC/rFyINua5ZbxzeREGgMvQE3FUnmIUyV65om0mALTTrxeiugKSbvq2ouQYm8pF3JOijDvgTNxDF77fomZB8OVaVckUFyhgiTDtspZpnr66JaYQc3+PiK4zHrl6wVWNUppao3j7WnWCcz4MUswmD5lcjIoQYlgFoP8+reE8MforTScxAiyt73C3fmbB1kxH/ejQpab7OA94sgAVgx69cMG+jvJZzLPLASSXC3X0vXJ9Zk9LKptC1UaOANF4pYGdX8u8EXyz6hvOXRrz0TKSDV80RnnZefQkcYyHh5q3cRgvxhzjpg/WcYfVer42eRPdvZ4p/8vCRsTVsPcMYf4YfOirZW+YDFKSlVe2+Gzj7Vhpkr98PkqBjqS8oJosQrZwNOxWp2CMQGVoDT9IFodUQrewYZo8/L0yNAqBq6Bd2jW1/1pC3zcMbo5vBqxr6weCY1iUvQUP+8U9Bhi9y78RRHwc9LNtYz71rD/jqxwoQ+jc75m3eT81AjX3L0CLH+pX01cQI/fmUYRzzh23EBEEm9OBNhkknTFLRBL5Ey5GMPIrjzEz/mR8UpGYUUh8AGK9B5CiZ0U1yVSbqkNhsyzngVsp4leLLDtfGYb0yzL9VE+c1f+iZE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
